//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSource.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice
    {
        public int invoice_id { get; set; }
        public Nullable<double> total_amt { get; set; }
        public Nullable<double> paid_amt { get; set; }
        public Nullable<double> discount { get; set; }
        public string agent_id { get; set; }
        public string dealer_name { get; set; }
        public string dealer_phone { get; set; }
        public string invoice_type { get; set; }
        public Nullable<int> purchase_id { get; set; }
        public Nullable<int> sale_id { get; set; }
        public Nullable<int> shop_id { get; set; }
    
        public virtual shop shop { get; set; }
        public virtual user user { get; set; }
    }
}
