//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSource.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase
    {
        public int purch_id { get; set; }
        public Nullable<int> prod_id { get; set; }
        public Nullable<int> prod_quant { get; set; }
    
        public virtual product product { get; set; }
    }
}
