//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSource.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SMS_DBEntities1 : DbContext
    {
        public SMS_DBEntities1()
            : base("name=SMS_DBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<brand> brands { get; set; }
        public virtual DbSet<inventory> inventories { get; set; }
        public virtual DbSet<product_types> product_types { get; set; }
        public virtual DbSet<shop> shops { get; set; }
        public virtual DbSet<msrmnt_units> msrmnt_units { get; set; }
        public virtual DbSet<purchase> purchases { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<sale> sales { get; set; }
    }
}
